#install.packages("ggmap")
library(ggmap)
mydata = read.csv("https://raw.githubusercontent.com/deyvidwilliam/cebd1160/master/data/3interventions_casernes_distance_2015_2017.csv")
casernes = data.frame(mydata$incident_nbr, mydata$caserne_longitude, mydata$caserne_latitude)
colnames(casernes) = c('incident','lon','lat')
mtl = as.numeric(geocode("Island of Montreal"))
MTLMap = ggmap(get_googlemap(center=mtl, scale=2, zoom=10), extent="normal")
MTLMap + geom_point(aes(x=lon, y=lat), data=casernes, col="blue", alpha=0.5)